name: Pyinstaller

on: 
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build-ubuntu:

    environment: env
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f action_requirements.txt ]; then pip install -r action_requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build for Ubuntu and upload
      run: |
        python -m PyInstaller wimmelbild2png.spec
    - uses: actions/upload-artifact@v3
      with:
          name: Ubuntu_Wimmelbildviewer
          path: dist/wimmelbild2png
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
