name: PyinstallerWindows

on: 
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build-windows:

    environment: env
    permissions: write-all
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r action_requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build for Windows and upload
      run: |
        python -m PyInstaller wimmelbild2png.spec
    - uses: actions/upload-artifact@v2
      with:
          name: Windows_Wimmelbildviewer
          path: dist/wimmelbild2png.exe
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "dist/wimmelbild2png.exe"
        allowUpdate: true
